"use client";

import { useEffect } from "react"
import confetti from "canvas-confetti"
import {
    BarChart3,
    Layers,
    ShieldAlert,
    FileText,
    CheckCircle2,
    AlertTriangle,
    Zap,
    Server,
    Globe,
    ArrowUpRight,
    Sparkles
} from "lucide-react"
import { DashboardSection } from "@/components/dashboard/DashboardSection"
import { KanbanBoard } from "@/components/kanban/KanbanBoard"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { Button } from "@/components/ui/button"

export default function DashboardPage() {
    useEffect(() => {
        const duration = 3 * 1000;
        const animationEnd = Date.now() + duration;
        const defaults = { startVelocity: 30, spread: 360, ticks: 60, zIndex: 0 };

        const randomInRange = (min: number, max: number) => Math.random() * (max - min) + min;

        const interval: any = setInterval(function () {
            const timeLeft = animationEnd - Date.now();

            if (timeLeft <= 0) {
                return clearInterval(interval);
            }

            const particleCount = 50 * (timeLeft / duration);
            confetti({ ...defaults, particleCount, origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 } });
            confetti({ ...defaults, particleCount, origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 } });
        }, 250);

        return () => clearInterval(interval);
    }, []);

    return (
        <div className="space-y-8 pb-12">
            {/* Header Info */}
            <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
                <div>
                    <div className="flex flex-wrap items-center gap-2 mb-1">
                        <Badge variant="success" className="bg-emerald-500/10 text-emerald-600 px-2 py-0 text-[10px]">LIVE PROJECT</Badge>
                        <span className="text-xs sm:text-sm text-slate-400 font-medium">Updated 2m ago</span>
                    </div>
                    <h1 className="text-2xl sm:text-3xl font-bold text-slate-900">EcoSwap Marketplace</h1>
                    <p className="text-sm sm:text-base text-slate-500 mt-1">Sustainable fashion trading platform with AI validation.</p>
                </div>
                <div className="flex flex-wrap items-center gap-3">
                    <Button variant="outline" className="flex-1 sm:flex-none gap-2 text-xs sm:text-sm h-10">
                        <FileText className="h-4 w-4" /> Export Plan
                    </Button>
                    <Button className="flex-1 sm:flex-none gap-2 shadow-lg text-xs sm:text-sm h-10 text-white">
                        <Sparkles className="h-4 w-4" /> AI Re-run
                    </Button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Main Doc Column */}
                <div className="lg:col-span-2 space-y-8">

                    {/* Executive Summary */}
                    <DashboardSection title="Executive Summary" icon={FileText} badge="Generated by Agent BA" badgeVariant="info">
                        <div className="space-y-4">
                            <p className="text-slate-600 leading-relaxed">
                                EcoSwap Marketplace aims to digitize the sustainable fashion circular economy. By leveraging AI for garment condition assessment and automated carbon footprint calculation, it provides a trusted platform for eco-conscious consumers to trade and resell fashion items.
                            </p>
                            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 pt-2">
                                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
                                    <span className="text-[10px] font-bold text-slate-400 uppercase block mb-1">Target Audience</span>
                                    <span className="text-sm font-semibold text-slate-700">Gen Z & Millennial Eco-shoppers</span>
                                </div>
                                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
                                    <span className="text-[10px] font-bold text-slate-400 uppercase block mb-1">Market Scope</span>
                                    <span className="text-sm font-semibold text-slate-700">Digital Resale ($77B by 2026)</span>
                                </div>
                                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
                                    <span className="text-[10px] font-bold text-slate-400 uppercase block mb-1">Revenue Model</span>
                                    <span className="text-sm font-semibold text-slate-700">12% Transaction Fee + Ads</span>
                                </div>
                            </div>
                        </div>
                    </DashboardSection>

                    {/* Architecture Overview */}
                    <DashboardSection title="Architecture Overview" icon={Layers} badge="Cloud Architect Approved" badgeVariant="success">
                        <div className="space-y-6">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div className="space-y-4">
                                    <h4 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                                        <Server className="h-4 w-4 text-primary" /> Backend Stack
                                    </h4>
                                    <ul className="space-y-2">
                                        <li className="flex items-center gap-2 text-sm text-slate-600">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500" /> Node.js / Express (TypeScript)
                                        </li>
                                        <li className="flex items-center gap-2 text-sm text-slate-600">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500" /> PostgreSQL with Prisma ORM
                                        </li>
                                        <li className="flex items-center gap-2 text-sm text-slate-600">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500" /> Redis for real-time caching
                                        </li>
                                    </ul>
                                </div>
                                <div className="space-y-4">
                                    <h4 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                                        <Globe className="h-4 w-4 text-primary" /> Infrastructure
                                    </h4>
                                    <ul className="space-y-2">
                                        <li className="flex items-center gap-2 text-sm text-slate-600">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500" /> AWS ECS (Fargate)
                                        </li>
                                        <li className="flex items-center gap-2 text-sm text-slate-600">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500" /> CloudFront CDN
                                        </li>
                                        <li className="flex items-center gap-2 text-sm text-slate-600">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500" /> S3 for Image Storage
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            <Separator />

                            <div>
                                <h4 className="text-sm font-bold text-slate-900 mb-3">System Traffic Flow</h4>
                                <div className="bg-slate-900 rounded-xl p-6 font-mono text-xs text-slate-300 overflow-x-auto">
                                    <pre>
                                        {`[Client] -> [Load Balancer] -> [API Gateway] 
                                    |
                    ---------------------------------
                    |               |               |
               [Auth Svc]      [Product Svc]   [Order Svc]
                    |               |               |
               [Redis Cache]   [PostgreSQL]    [Payment API]`}
                                    </pre>
                                </div>
                            </div>
                        </div>
                    </DashboardSection>

                    {/* Kanban Section */}
                    <div className="pt-4">
                        <div className="flex items-center justify-between mb-4">
                            <h2 className="text-2xl font-bold flex items-center gap-3">
                                <Zap className="h-6 w-6 text-primary" />
                                Sprint Kanban Board
                            </h2>
                            <Button variant="ghost" className="text-primary hover:bg-primary/5 font-medium">View All Issues</Button>
                        </div>
                        <KanbanBoard />
                    </div>
                </div>

                {/* Sidebar Column */}
                <div className="space-y-8">

                    {/* Business Insights */}
                    <DashboardSection title="Business Insights" icon={BarChart3} badge="High Potential" badgeVariant="warning">
                        <div className="space-y-6">
                            <div className="p-4 rounded-xl bg-slate-50 border border-slate-100">
                                <div className="flex justify-between items-start mb-2">
                                    <span className="text-sm font-bold text-slate-700">Market Fit Score</span>
                                    <span className="text-xl font-bold text-primary">92/100</span>
                                </div>
                                <div className="w-full bg-slate-200 h-2 rounded-full overflow-hidden">
                                    <div className="bg-primary h-full w-[92%]" />
                                </div>
                            </div>

                            <div className="space-y-3">
                                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Key KPIs to Track</h4>
                                <ul className="space-y-3">
                                    <li className="bg-white border rounded-lg p-3 shadow-sm hover:translate-x-1 transition-transform cursor-pointer group">
                                        <div className="flex justify-between items-center">
                                            <span className="text-sm font-medium">Platform CAC</span>
                                            <ArrowUpRight className="h-4 w-4 text-slate-300 group-hover:text-primary transition-colors" />
                                        </div>
                                    </li>
                                    <li className="bg-white border rounded-lg p-3 shadow-sm hover:translate-x-1 transition-transform cursor-pointer group">
                                        <div className="flex justify-between items-center">
                                            <span className="text-sm font-medium">Retention (Day 30)</span>
                                            <ArrowUpRight className="h-4 w-4 text-slate-300 group-hover:text-primary transition-colors" />
                                        </div>
                                    </li>
                                    <li className="bg-white border rounded-lg p-3 shadow-sm hover:translate-x-1 transition-transform cursor-pointer group">
                                        <div className="flex justify-between items-center">
                                            <span className="text-sm font-medium">Transaction Velocity</span>
                                            <ArrowUpRight className="h-4 w-4 text-slate-300 group-hover:text-primary transition-colors" />
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </DashboardSection>

                    {/* Risk Analysis */}
                    <DashboardSection title="Risk Analysis" icon={ShieldAlert} badge="3 Critical" badgeVariant="destructive">
                        <div className="space-y-4">
                            <div className="flex gap-3 p-3 rounded-xl bg-destructive/5 border border-destructive/10">
                                <AlertTriangle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
                                <div>
                                    <h4 className="text-sm font-bold text-slate-900">Legal Compliance (GDPR)</h4>
                                    <p className="text-xs text-slate-600 mt-1">Requirement for robust data deletion policies due to EU users.</p>
                                </div>
                            </div>
                            <div className="flex gap-3 p-3 rounded-xl bg-amber-500/5 border border-amber-500/10">
                                <AlertTriangle className="h-5 w-5 text-amber-500 shrink-0 mt-0.5" />
                                <div>
                                    <h4 className="text-sm font-bold text-slate-900">Scalability Bottleneck</h4>
                                    <p className="text-xs text-slate-600 mt-1">Image processing for AI validation might require async workers.</p>
                                </div>
                            </div>
                            <div className="flex gap-3 p-3 rounded-xl bg-blue-500/5 border border-blue-500/10">
                                <AlertTriangle className="h-5 w-5 text-blue-500 shrink-0 mt-0.5" />
                                <div>
                                    <h4 className="text-sm font-bold text-slate-900">Payment Gateway Lag</h4>
                                    <p className="text-xs text-slate-600 mt-1">Cross-border payout processing can take up to 7 days.</p>
                                </div>
                            </div>
                            <Button variant="outline" className="w-full text-xs font-bold text-slate-600 mt-2">Generate Full Report</Button>
                        </div>
                    </DashboardSection>
                </div>
            </div>
        </div>
    )
}
